name: CI to Aliyun Server

on:
  push:
    branches:
      - master # 或您的特定部署分支
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置环境变量
    - name: Set environment variables
      run: |
        echo "IMAGE_AND_CONTAINER_NAME=hello_py" >> $GITHUB_ENV
        echo "CURRENT_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    # SSH 登录到服务器并部署
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_KEY }}
        port: ${{ secrets.ALIYUN_PORT }} # 如果修改了默认的 SSH 端口，请在此修改
        script: |
          # 项目目录，替换为您的项目真实路径
          cd ~/workdir/hello_python
          
          # 创建镜像，使用基础名加上时间戳
          docker build -t ${{ env.IMAGE_AND_CONTAINER_NAME }}:${{ env.CURRENT_DATE }} .

          # 停止并删除旧的容器
          docker stop ${{ env.IMAGE_AND_CONTAINER_NAME }} || true
          docker rm ${{ env.IMAGE_AND_CONTAINER_NAME }} || true

          # 运行新的 Docker 容器，使用新的镜像
          docker run -d --name ${{ env.IMAGE_AND_CONTAINER_NAME }} ${{ env.IMAGE_AND_CONTAINER_NAME }}:${{ env.CURRENT_DATE }}

          # 清理旧的镜像，可选 
          # docker image prune -a -f --filter "until=24h"
